# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: smartchat publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checks out your repository onto the runner
        uses: actions/checkout@v3
      - name: use pnpm for installing and caching your dependencies # https://www.pnpm.cn/continuous-integration
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - name: install the specified version of the Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - run: pnpm run build
      - name: upload artifact # upload build products
        uses: actions/upload-artifact@v3
        with: 
          name: build
          path: build
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    # Publishing packages with provenance via GitHub Actions https://docs.npmjs.com/generating-provenance-statements
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          registry-url: https://registry.npmjs.org/
      - name: download artifacts # download build products
        uses: actions/download-artifact@v3
        with: 
          name: build
          path: build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
